### ISSUE TITLE
Keep or delete this app? 

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterAppsFreezer/AppStoreClient#41]
For https://github.com/Starcounter/CompanyTrack/issues/331

**Delete?** If this is what it seems to be, an app to help users find and download apps, it's outdated and will soon be replaced. I'm not sure if it's used at all.

**Comment by warpech** [comment]
This is a question to @andwah. I assume this app does not work anymore, since the old warehouse was removed from Administrator?

**Comment by andwah** [comment]
Current pushed version does not work.

I was thinking like this:  "Merge" WarehouseClient with "AppStoreClient" and rename this repo "AppStore", and then delete "WarehouseClient" repo.

I suggest that we keep this app repo (maybe make it private?).

**Comment by Mackiovello** [comment]
> I suggest that we keep this app repo (maybe make it private?).

Maybe it would be possible to move to the freezer?

**Comment by andwah** [comment]
> Maybe it would be possible to move to the freezer?

Sound okey for me.

**Comment by warpech** [comment]
Next steps:

- [ ] Make a PR that explains the purpose of this app for future reference.
- [x] Move this app to https://github.com/StarcounterAppsFreezer. Apps in that organisation do not get updates until we remove them from freezer.

@andwah could you please do the PR that explains the purpose of this app for future reference? All apps in the freezer should have that.

**Comment by andwah** [comment]
@warpech Just created a PR.

**Comment by warpech** [comment]
All done now, app moved to StarcounterAppsFreezer

**Comment by warpech** [comment]
> I was thinking like this: "Merge" WarehouseClient with "AppStoreClient" and rename this repo "AppStore", and then delete "WarehouseClient" repo.

Wouldn't it be simpler to just remove this repo `AppStoreClient` and rename what now is `WarehouseClient` to `AppStore`? Then no merges needed.

**Comment by andwah** [comment]
> Wouldn't it be simpler to just remove this repo AppStoreClient and rename what now is WarehouseClient to AppStore? Then no merges needed.

Yes. much simpler :-)

**Comment by warpech** [comment]
Great! I will archive this app on Dropbox and delete it from GH

**Comment by Mackiovello** [comment]
Closing as it is moved to the freezer
